language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-head
gemfile:
  - gemfiles/ar_4.2.gemfile
  - gemfiles/ar_5.0.gemfile
matrix:
  fast_finish: true
before_install: gem install bundler -v 1.11.2
script: bundle exec rake spec
