language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-head
gemfile:
  - gemfiles/ar_3.2.gemfile
  - gemfiles/ar_4.0.gemfile
  - gemfiles/ar_4.1.gemfile
  - gemfiles/ar_4.2.gemfile
before_install: gem install bundler -v 1.11.2
script: bundle exec rake spec
